name: build-iso
on: workflow_dispatch
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Free disk space
        run: sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/lib/android
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/hellbraker9/my-atomic:latest
      - uses: osbuild/bootc-image-builder-action@main
        with:
          config-file: ./config.toml
          image: ghcr.io/YOURUSER/my-atomic:latest
          type: anaconda-iso
      - uses: actions/upload-artifact@v4
        with:
          name: iso
          path: output/bootiso/*.iso